import { Component, signal, WritableSignal, inject } from '@angular/core';
import { FormsModule } from '@angular/forms'; // needed for ngModel
import { StudentService } from '../student'
import { Student } from '../student.model';

@Component({
  selector: 'app-student-crud',
  standalone: true,
  imports: [FormsModule], // no CommonModule needed, new control flow (@if/@for) is built-in
  templateUrl: './student-crud.html',
  styleUrl: './student-crud.css',
})
export class StudentCrud {

  // inject the service (same pattern as your HttpClient example)
  studentService = inject(StudentService);

  // pull the signal from the service so template can read it
  students = this.studentService.getStudents();

  // form model - one object used for BOTH add and edit
  form: WritableSignal<Student> = signal<Student>(this.emptyStudent());

  // track whether we are editing (null = add mode, id = edit mode)
  editingId: WritableSignal<number | null> = signal(null);

  // returns a blank student object, used to reset the form
  emptyStudent(): Student {
    return { id: 0, name: '', email: '', marks: 0 };
  }

  // called when "Save" button is clicked
  onSubmit() {
    const value = this.form();

    // basic validation
    if (!value.name || !value.email) {
      alert('Name and Email are required');
      return;
    }

    if (this.editingId() === null) {
      // ADD mode - id is auto generated by service
      const { id, ...rest } = value;
      this.studentService.addStudent(rest);
    } else {
      // EDIT mode - update existing student
      this.studentService.updateStudent({ ...value, id: this.editingId()! });
    }

    this.resetForm();
  }

  // called when clicking "Edit" on a row -> loads that student into the form
  onEdit(student: Student) {
    this.form.set({ ...student }); // spread to avoid editing original object directly
    this.editingId.set(student.id);
  }

  // called when clicking "Delete" on a row
  onDelete(id: number) {
    if (confirm('Delete this student?')) {
      this.studentService.deleteStudent(id);
    }
  }

  // cancel edit / clear form
  resetForm() {
    this.form.set(this.emptyStudent());
    this.editingId.set(null);
  }

  // helper to update a single field in the form signal (used via (input) events)
  updateField(field: keyof Student, value: string) {
    this.form.update(f => ({
      ...f,
      [field]: field === 'marks' ? Number(value) : value,
    }));
  }
}
